# Generated by Django 5.2 on 2025-05-03 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colorblind_type', models.CharField(choices=[('protanopia', 'Protanopia (Red-Blind)'), ('deuteranopia', 'Deuteranopia (Green-Blind)'), ('tritanopia', 'Tritanopia (Blue-Blind)'), ('achromatomaly', 'Achromatomaly (Color Weakness)')], max_length=20)),
                ('issues_count', models.PositiveIntegerField(default=0)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('analysis_data', models.JSONField(default=dict)),
                ('project_name', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyzer.project')),
            ],
        ),
    ]
