# Generated by Django 5.2 on 2025-04-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colorblind_type', models.CharField(choices=[('protanopia', 'Protanopia (Red-Blind)'), ('deuteranopia', 'Deuteranopia (Green-Blind)'), ('tritanopia', 'Tritanopia (Blue-Blind)'), ('achromatomaly', 'Achromatomaly (Color Weakness)')], max_length=20)),
                ('issues_count', models.PositiveIntegerField(default=0)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('analysis_data', models.JSONField(default=dict)),
            ],
        ),
    ]
