# Generated by Django 5.2 on 2025-05-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
