# Generated by Django 5.2 on 2025-05-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_project_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
